# .properties ? ????? ?? ?? (ex. spring.application.name=basic    datasource.??? = ???    datasource.???=???)
# .yml or .yaml ? ?? ???? ???? ??

# port ?? ???  // (local) default ? 8080 ???..
#server:
#  port: 8081    # ?? ??? port kill

# ???? ???? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234 # ????..? .gitignore??..? ????? ???? ????~ ??? ?????(????? ????? ??)? ?? ?? ?? ?????~